export const init = 'init.ts'
export const setActiveView = 'setActiveView'
export const setFolderExpandedFolderKey = 'setFolderExpandedFolderKey'
export const addExpandedFolderKey = 'addExpandedFolderKey'
export const deleteExpandedFolderKey = 'deleteExpandedFolderKey'
